name: flutter_map_booking
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.13
  flutter_google_places: ^0.2.6
  location: ^2.3.5
  http: 0.12.0+3
  font_awesome_flutter: ^8.8.1
  flutter_spinkit: ^4.1.2+1
  flutter_rating_bar: ^3.0.1+1
  intro_views_flutter: ^2.8.0
  pin_code_text_field: ^1.7.1
  image_picker: ^0.6.6+5
  geolocator: ^5.3.1 #Use this version packages to get the best performance
  geocoder: ^0.2.1
  latlong: ^0.6.1
  dio: ^3.0.9
  json_annotation: ^3.0.1
  flutter_swiper: ^1.1.6
  fl_chart: ^0.9.3
  cached_network_image: ^2.1.0+1
  flutter_slidable: ^0.5.7
  material_design_icons_flutter: ^4.0.5555
  flutter_staggered_animations: ^0.1.2
  sliding_up_panel: ^1.0.2
  provider: ^4.3.2+3
  grouped_buttons: ^1.0.4
  url_launcher: ^5.4.5
  flutter_svg: ^0.18.1
  webview_flutter: ^0.3.20+2
  permission_handler: ^5.0.0
  toast: ^0.1.5
  outline_material_icons: ^0.1.1
  shared_preferences: '>=0.5.12+4 <2.0.0'
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.3
  cloud_firestore:
  carousel_slider: ^2.1.0

  flutter_driver:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.5


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/icon_taxi/
    - assets/style/
    - assets/image/svg/
    - assets/image/marker/
    - lib/i18n/ar.json
    - lib/i18n/en.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

    - family: Sultan
      fonts:
        - asset: assets/fonts/sultan.ttf

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: Lucida
      fonts:
        - asset: assets/fonts/LUCON.TTF
